# frozen_string_literal: true

# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

begin
  saved_verbose = $VERBOSE
  $VERBOSE = nil
  require_relative 'config/application'
ensure
  $VERBOSE = saved_verbose
end

Rails.application.load_tasks
